#pragma once
#include "configuracion.h"
#include "../../comun/nodo_mesh.h"
#include "mesh_storage.h"
#include "envio_persistente.h"
#include "politica_envio.h"
#include <OneWire.h>
#include <DallasTemperature.h>
#include <U8g2lib.h>
#include <RTClib.h>
#include <Wire.h>

OneWire wireFridge(ICIV_FRIDGE_PIN),wireFreezer(ICIV_FREEZER_PIN);
DallasTemperature fridge(&wireFridge),freezer(&wireFreezer);
DallasTemperature* probes[2]={&fridge,&freezer};
U8G2_SH1106_128X64_NONAME_F_HW_I2C oled(U8G2_R0,U8X8_PIN_NONE);
RTC_DS3231 rtc;
Journal journal;
MeshStorage store;
EnvioProtegido flight={};
EnvioPersistente flightStore;
bool rtcOk=false,clockOk=false,storageOk=false,radioOk=false;
float latest[2]={NAN,NAN};
bool sensorKnown[2]={false,false},snapshotPending=true;
uint32_t lastMeasure[2]={0,0},conversionStart=0,conversionEpoch=0,displayAt=0,cutEpoch=0;
uint8_t dueMask=0;
bool conversion=false,captureCut=false,needsFirst=false,sampleClock=false;
bool battery=false,powerCandidate=false,powerSeen=false;
uint32_t powerChangedAt=0,reportAt=0;
enum LinkState { UNKNOWN,ONLINE,GATEWAY_DOWN,CENTRAL_DOWN };
LinkState linkState=UNKNOWN;
PoliticaEnvio delivery;
